<a href="https://colab.research.google.com/github/olumidedaramola21/ml/blob/main/NumPy_UltraQuick.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5]
)
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
two_dimensional_array = ([6, 5], [11, 7], [4, 8])
print(two_dimensional_array)

([6, 5], [11, 7], [4, 8])


In [5]:
sequence_of_intergers = np.arange(5, 12)
print(sequence_of_intergers)

[ 5  6  7  8  9 10 11]


In [6]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=100, size=(6,))
print(random_integers_between_50_and_100)

[55 65 79 71 53 92]


In [8]:
random_floats_between_0_and_1 = np.random.random((6,))
print(random_floats_between_0_and_1)

[0.30536098 0.30422264 0.48687757 0.08882626 0.8173018  0.17122133]


In [10]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.30536098 2.30422264 2.48687757 2.08882626 2.8173018  2.17122133]


In [11]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[165 195 237 213 159 276]


In [17]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [18]:
noise = (np.random.random(15) * 4) -2
print(noise)

[-0.18132615 -0.08871899  0.14699307 -1.51055238 -1.89377466 -1.8230538
 -0.94870261  1.47305895  1.46570053  1.49224477 -1.80718468  1.55482913
 -1.59447912 -0.99634657  1.18443066]
