<a href="https://colab.research.google.com/github/olumidedaramola21/pytorch/blob/main/001/001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("olumide")

olumide


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [3]:
#MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [4]:
MATRIX.ndim

2

In [5]:
MATRIX.shape


torch.Size([2, 2])

In [8]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [9]:
TENSOR.ndim

3

In [10]:
TENSOR.shape

torch.Size([1, 3, 3])

Creating tensors
Pytorch tensors are created using torch.Tensor()


In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])