<a href="https://colab.research.google.com/github/olumidedaramola21/pytorch/blob/main/001/001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("olumide")

olumide


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape


torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

Creating tensors
Pytorch tensors are created using torch.Tensor()


In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## RANDOM TENSOR

In [8]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,  3 , 2))
random_tensor, random_tensor.dtype

(tensor([[[0.4187, 0.8546],
          [0.3420, 0.4159],
          [0.8339, 0.2550]],
 
         [[0.7669, 0.4225],
          [0.8284, 0.0947],
          [0.6007, 0.0732]],
 
         [[0.2446, 0.6520],
          [0.9295, 0.2669],
          [0.0727, 0.5225]]]),
 torch.float32)

Zeros and ones

In [10]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)